### ISSUE TITLE
unstable anomaly issue

### ISSUE THREAD

**Issue by Mundzso** [ZyRaNex/ZyHelper#10]
If the wizard's unstable anomaly passiv activates the meteor will usually fail or won't shoot at all.

**Comment by ZyRaNex** [comment]
I have not encountered this. If you have a clip please send it to me.
If anyone else has the same problem please tell me.

**Comment by Mundzso** [comment]
The workaround for me was to replace the unstable anomaly e.g.: with blur passiv. But it doesnt' matter for me now, I bought a logitech mouse.
ZyHelper is a great tool tho, very nice work :) love it ! ( for lon rats especially and for old wiz) but for lon32 wizard gr 148+ few failed and/or no meteor makes it hard to succeed. I heard that top players are using mouse/keyboard stuff, not sure if its true. Although I still need some good macro for the mouse but noone is going to share it :)

**Comment by ZyRaNex** [comment]
I never had that issue and i cleared 150 with unstable anomaly. Do you have any idea why it could fail?

**Comment by Mundzso** [comment]
You guys are using your tool for 150 clears and never a failed or not shooting meteor? 
Yes, my guess was that when unstable anomaly activates right 1-2sec before the arcane meteor it releases a shockwave which overwrites the helper and stops it casting the meteor (just a wild guess).
Altough as I said in an other issue, sometimes the meteor is not casting at all, passiv or no passiv, maybe serverlagg/too many mobs / afixes vs coe communication , I don't know :( But when this happens all my stacks are lost and we just pray that the next circle will be OK. 
The failed meteors (where the meteor is casted, but with failed channeling state, incorrect archon activation time) is another kind of fail, which is usually only noticable in high GR-s, but this is because of density/lagg I guess.

**Comment by Mundzso** [comment]
Anyway if I'm alone with this issue and you guys are clearing 150s with this, feel free to close my issues :) It is possible that I have some kind of local issues or something.
One more guess: do you think I should always hold down electrocute too and not releasing it before meteors? I mean isn't it possible that this can cause failed meteors too and I should only hold down macro key in the key moment? You always hold down both buttons as you said in the guide, yes?

**Comment by ZyRaNex** [comment]
Yeah i always hold down both buttons.
If you can record your gameplay + helper and send it to me maybe i can figure it out.
