### ISSUE TITLE
No Archon

### ISSUE THREAD

**Issue by XiansaiX** [ZyRaNex/ZyHelper#11]
When I press and hold button 2 and 5 the macro does all the right rotation in right COE cycles BUT BUT it DOES NOT press Left Mouse Button to enter Archon. Am I doing something wrong here?
![Skærmbillede (26)](https://user-images.githubusercontent.com/49659416/56354261-8d696880-61d3-11e9-9f82-2739e95fed32.png)

**Comment by ZyRaNex** [comment]
Try unchecking the blackhole checkbox

**Comment by XiansaiX** [comment]
Does not help :-( It's like LM does not respond. Tried putting blackhole on LMB and Archon on RMB. Then just no Blackhole, but enters Archon

**Comment by ZyRaNex** [comment]
Maybe its something with shift. Do you hold it down yourself?

**Comment by XiansaiX** [comment]
Made it work :-) Thx

**Comment by ZyRaNex** [comment]
how did you fix it?

**Comment by XiansaiX** [comment]
was the keybindings :-)
