### ISSUE TITLE
error CS0103: The name 'ActorSnoEnum' does not exist in the current context

### ISSUE THREAD

**Issue by YawataNoKami** [ZyRaNex/ZyHelper#5]
Hello
When i start ZyHelperBeta and then TH i get error on TH that said (from logs) :
Downloads\TurboHUD 19.1.25.1 (v8.0) BETA for Diablo III 2.6.4.55430 (64 bit)\Plugins\Zy\ZyHelperBetaAdapter.cs(216,46) : error CS0103: The name 'ActorSnoEnum' does not exist in the current context 

Where this problem come from ? 
Thx

**Comment by ibushk** [comment]
Upgrade THUD to v9.0
