### ISSUE TITLE
meteor timing

### ISSUE THREAD

**Issue by Mundzso** [ZyRaNex/ZyHelper#6]
First of all thank you so much for this tool. It is really nice.
I tested it a few hours. I noticed that the meteor in arcane lands in the last 1< sec and this gives the archon so little window that it will eventually make the meteor fail (will not have archon cd available in time) due to delay/lagg.
I think it should shoot the arcane meteor just a little bit earlier like 2<sec or so.

**Comment by ZyRaNex** [comment]
Fixed with version 1.2.14.
Now enters archon at ~2s arcane.
