### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by ibushk** [ZyRaNex/ZyHelper#7]
Thanks for your macro.
I try to follow your instruction and seems all activated except automates button presses not running as below screen cap. Any idea?

![screen_cap00](https://user-images.githubusercontent.com/48654622/54608194-26994800-4a8b-11e9-9f6a-4414bcd0d714.jpg)

**Comment by ZyRaNex** [comment]
Hm it looks like it should be working.
Are you sure its not casting the skills?
Keep in mind that you need to press electrocute yourself.
Is this on the chinese game client?
Try opening chat to see if it actually presses the buttons.

**Comment by ibushk** [comment]
Hi,
I figured out the problem should be caused by D3 game language, it seems only worked in English.
Thanks anyway!!
