### ISSUE TITLE
NOT running too.

### ISSUE THREAD

**Issue by bema0920** [ZyRaNex/ZyHelper#8]
![11111](https://user-images.githubusercontent.com/48822803/54861836-2c857680-4d74-11e9-8928-d80bff8ac0ab.png)

Thanks.

This macro and you HUD plugin is very good idea.

ZyHelper is no response when 5 is pressed.

Tell me how to do it.

I want to this macro~

Thanks

**Comment by ibushk** [comment]
You may try to change D3 language to English and then test again

**Comment by bema0920** [comment]
thanks ibushk
Macro works in English.
